10 CLS
20 INPUT “NOUN”; A$
30 INPUT “ADJECTIVE”; B$
40 INPUT “NOUN”; C$
50 INPUT "NOUN”; D$
60 INPUT "VERB”; E$
70 INPUT "ADVERB”; F$
80 INPUT "ADJECTIVE”; G$
90 CLS
100 PRINT “TODAY, I WENT TO A” A$ “MUSEUM.”
110 PRINT “THERE WAS A” B$ C$ “AND A” D$ “THAT” E$ “.”
120 PRINT “WE WALKED THROUGH THE BUILDINGS” F$
130 PRINT “AND HAD LOTS OF” G$ “FUN!”
140 PRINT “I CAN’T WAIT TO GO BACK TO THE” A$ “MUSEUM!”
150 END